# Generated by Django 4.1.6 on 2023-02-20 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_emailverificationtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_be_verified_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
