# Generated by Django 4.1.6 on 2023-02-24 11:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='added_by',
            field=models.ForeignKey(default=datetime.datetime(2023, 2, 24, 11, 55, 14, 238940, tzinfo=datetime.timezone.utc), editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='added_transactions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
