# Generated by Django 4.1.6 on 2023-03-07 18:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_transaction_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RunSQL("DROP TABLE IF EXISTS api_income"),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Bonus', 'Bonus'), ('Commission', 'Commission')], max_length=15)),
                ('description', models.CharField(max_length=50)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunSQL("DROP TABLE IF EXISTS api_expense"),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Beverage', 'Beverage'), ('Lend/Borrow', 'Lend/Borrow'), ('Entertainment', 'Entertainment'), ('Utility', 'Utitity'), ('Other', 'Other')], max_length=15)),
                ('description', models.CharField(max_length=50)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
