# Generated by Django 4.1.6 on 2023-03-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_transaction_amount_income_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(default='E', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='income',
            name='type',
            field=models.CharField(default='I', editable=False, max_length=10),
        ),
    ]
