# Generated by Django 4.1.6 on 2023-03-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_expense_type_income_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Bonus', 'Bonus'), ('Commission', 'Commission'), ('Other', 'Other')], max_length=15),
        ),
    ]
