name: Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: 20.127.16.187 
          username: ubuntu
          key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
          script: |
            cd /var/www/myfinance
            git pull origin main
            python3 manage.py makemigrations
            python3 manage.py migrate
            python3 manage.py collectstatic --noinput
            sudo systemctl restart myfinance
